version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
#            - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
#            - AIRFLOW__SMTP__SMTP_USER=spietrzak@gmail.com
#            - AIRFLOW__SMTP__SMTP_PASSWORD=aqsrtzoyxatirurp
#            - AIRFLOW__SMTP__SMTP_PORT=587
#            - AIRFLOW__SMTP__SMTP_MAIL_FROM=spietrzak@oanda.com
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./logs:/usr/local/airflow/logs
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
